// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1Si-1OiAuwvAAPSL1J4TmNbf8r_Uv1EY',
    appId: '1:367593452741:web:3be7f03fbcc2015d97acac',
    messagingSenderId: '367593452741',
    projectId: 'swapshop-4660b',
    authDomain: 'swapshop-4660b.firebaseapp.com',
    storageBucket: 'swapshop-4660b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD9YQqup8NLvyucUSTDLrmDoQJPEtZz9o',
    appId: '1:367593452741:android:c62a59d8818631cb97acac',
    messagingSenderId: '367593452741',
    projectId: 'swapshop-4660b',
    storageBucket: 'swapshop-4660b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBihuEiqNYNdkJMdPafCgsE6nHH1ZrU_eo',
    appId: '1:367593452741:ios:55c084659a3c0fda97acac',
    messagingSenderId: '367593452741',
    projectId: 'swapshop-4660b',
    storageBucket: 'swapshop-4660b.firebasestorage.app',
    iosBundleId: 'com.example.swapCustApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBihuEiqNYNdkJMdPafCgsE6nHH1ZrU_eo',
    appId: '1:367593452741:ios:55c084659a3c0fda97acac',
    messagingSenderId: '367593452741',
    projectId: 'swapshop-4660b',
    storageBucket: 'swapshop-4660b.firebasestorage.app',
    iosBundleId: 'com.example.swapCustApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1Si-1OiAuwvAAPSL1J4TmNbf8r_Uv1EY',
    appId: '1:367593452741:web:8bd96ec8536b7fcd97acac',
    messagingSenderId: '367593452741',
    projectId: 'swapshop-4660b',
    authDomain: 'swapshop-4660b.firebaseapp.com',
    storageBucket: 'swapshop-4660b.firebasestorage.app',
  );
}
